#!/bin/bash
# Prevents direct editing of auto-generated RBS type definition files.
# Type definitions in */sig/ directories are managed by PostToolUse hooks.

# Hook input is JSON from stdin
input=$(cat)
tool_name=$(echo "$input" | jq -r '.tool_name // ""')

# Block Write/Edit operations on sig/ files
if [[ "$tool_name" == "Write" || "$tool_name" == "Edit" ]]; then
    file_path=$(echo "$input" | jq -r '.tool_input.file_path // ""')

    if [[ "$file_path" == */sig/* || "$file_path" == sig/* ]]; then
        echo "❌ ERROR: Direct editing of sig/ files is not allowed." >&2
        echo "📝 Type definitions are auto-generated by PostToolUse hook." >&2
        echo "💡 Modify inline RBS annotations in .rb files instead." >&2
        exit 2
    fi
fi

# Block manual rbs-inline execution
if [[ "$tool_name" == "Bash" ]]; then
    command=$(echo "$input" | jq -r '.tool_input.command // ""')

    # Match rbs-inline only at a command position, not as an argument.
    rbs_inline_re=$'(^|[;&|(\n])[[:space:]]*(bundle[[:space:]]+exec[[:space:]]+)?([^[:space:]]*/)?rbs-inline([[:space:]]|[;&|)]|$)'

    if [[ "$command" =~ $rbs_inline_re ]]; then
        echo "❌ ERROR: Manual rbs-inline execution is not allowed." >&2
        echo "🔄 Type definitions are auto-generated by hooks." >&2
        exit 2
    fi
fi

exit 0
